#!/usr/bin/env bash
#
# Sync sublime settings

rm -rf ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
ln -s $ZSH/sublime/settings/ ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
